apiVersion: v1
kind: Service
metadata:
  name: tiling-service
spec:
  selector:
    app: tiling
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiling
spec:
  selector:
    matchLabels:
      app: tiling
  replicas: 3
  template:
    metadata:
      labels:
        app: tiling
    spec:
      containers:
      - name: tiling
        image: lingyixu/tiling:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
